### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by v-tron**
Hi,

I tried to improve the overall aesthetic of the table. 

- Changed the location images to be compatible with a green background 
- Tried to improve several of the descriptions to be more brief/concise
- Picked default colors which improve readability of the white text
- Changed Text to Bold for improved readability
- Changed Lab enchant image to bigger/higher resolution icon
- Fixed empty images having a pixel in the middle by setting opacity to 0. This can be seen when picking a background color
- Changed Table border color slightly to be a tad more visible

If you have any complaints/suggestions let me know.

This is an example Table with default colors:
syndicate_table_example

### CODE REVIEW

**Comment by dbjorge** [comment]
This all looks good to me with the exception of the updated default background colors; subjectively, I find the updated ones less readable. Objectively, the best measure I'm available of text color readability is to use the [Web Content Accessibility Guidelines' Contrast test](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html). [WebAIM's contrast checker](https://webaim.org/resources/contrastchecker/), shows the following contrast ratios (higher is better):

| | Great | Maybe | Ignore |
| - | - | - | - |
| Old color | #0a5511 | #54550a | #590404 |
| Old contrast | 9.05:1 | 7.83:1 | 14.54:1 |
| New color | #036305 | #c27e00 | #8f1100 |
| New contrast | 7.52:1 | 3.34:1 | 9.34:1 |

The green and red aren't so bad, but the proposed yellow is particularly hard for me to read (it's the only case that doesn't pass the 7:1 minimum WCAG recommends for this size of text)

**Comment by v-tron** [comment]
That is really weird, since I purposefully chose a more orange/dark hue for the "yellow" than the one that was in originally and that should translate into more contrast against white than a lighter/more yellow color and not less.

I will revisit this tomorrow and maybe change it back. In any case it would be nice to be able to select a color yourself on the page. I thought this was possible initially but it's not. Not sure how hard it would be to implement.

**Comment by v-tron** [comment]
I actually thought that the lightest yellow was default, seems like I was wrong.

So yes, it is probably better to keep the old defaults then. Maybe tweak the overall selection a little since the only actually yellow color in there was even less contrasty than my selection. White on yellow is just impossible to read if you have a bright yellow. I will change the defaults back tomorrow and post another pull request after.

**Comment by v-tron** [comment]
I redid the whole color selection to follow a gradient from dark to light and picked the darkest (most contrasty) color as default.

**Comment by Multigrain** [comment]
Looks good. I'll leave it here for a lil before merging to see if any comments on colours otherwise its good to go.

Interesting information about the colours. I originally just chose colours that I could read the text on the best while keeping it stoplight colours like the original cheatsheets. Yellow being the most annoying to get right. I forgot about there being a metric for measuring readability via contrast, which I'll remember going forward. Might be worth adding an option to change font colour too, allowing more background choices while keeping readability. but I weighed that in past and wanted to keep the page/clutter down to a minimum.

I can't believe you found and that there even exists a single pixel in the empty images haha. I just hid all layers and made it as a lazy/simple way to keep formatting the same so I'm surprised that its there, must have hit it with the brush tool by accident. Great find.

**Comment by dbjorge** [comment]
Thanks @v-tron, the updated colors are much more readable by default now! I suspect you probably want to update L14-16 to match the other color changes; otherwise, looks good to me!

**Comment by v-tron** [comment]
@dbjorge thanks for the heads up, I just updated them there as well.

**Pull request merged**
