### PR TITLE
Initial update for 3.14

### LINKED ISSUE #2: CheatSheet outdated
It should be updated as follow

image

Source: https://www.reddit.com/r/pathofexile/comments/mx95a0/314_updated_betrayal/

### PR DESCRIPTION
**Pull request by dbjorge**
This PR updates the table using what information I was able to find for 3.14. Fixes #2.

Screenshot of updated table, with text-only updates in yellow and text+image updates in green:
screenshot of PR with changes highlighted

I removed most of the information on the timing for Guff since there seems to be some consensus that it's changed but only a little bit of info on what the new values are. [This](https://www.reddit.com/r/pathofexile/comments/mx690x/vorici_4_star_16_white_sockets/gvmxxd0/) suggests that T4 research is 40s, [this](https://www.reddit.com/r/pathofexile/comments/mx95a0/314_updated_betrayal/gvn98nt/) suggests T2 research is 30s.

Elreon T/F/R, Jorgin T/F/R, and Tora R each list per-tier effects that I wasn't able to find any new 3.14 information for. I've left them alone for now, hopefully someone will test them and we can update them further later.

The primary sources I'm using for the updated info are:
* carefuldownvoter91 reddit posts ([1](https://www.reddit.com/r/pathofexile/comments/mx690x/vorici_4_star_16_white_sockets/gvm8863/), [2](https://www.reddit.com/r/pathofexile/comments/mx6ufr/314_updated_betrayal/gvmqbih/))
* FixFaxer's Cheat Sheet ([PoE Forum Thread](https://www.pathofexile.com/forum/view-thread/2451569/page/1), [Google Sheet](https://docs.google.com/spreadsheets/d/1fIs8sdvgZG7iVouPdtFkbRx5kv55_xVja8l19yubyRU/edit#gid=1814105689))

I also added a non-placeholder page title/favicon while I was making changes anyway.

### CODE REVIEW

**Comment by dbjorge** [comment]
@Multigrain , are you the right person to request a review from? I'm not sure whether you're still interested in making updates to this project, since it's been 1yr+ since the last commit; I don't mind forking the project if you've moved on to other games/projects, but I thought I'd send a PR first for the sake of folks using the existing https://poetools.github.io/BetrayalCheatSheet/ URL

**Comment by v-tron** [comment]
Hey I just thought about updating this and you already did it. Very nice work!

**Comment by dbjorge** [comment]
@v-tron I'm glad there are other folks that would be interested in using it! If you're interested in helping, it would be great to have a second person double check whether I've missed any updates or info sources

**Comment by v-tron** [comment]
I'll gladly help, gonna look over it, no problem.

**Comment by v-tron** [comment]
@dbjorge can you create a function to export the table as a jpg?

**Comment by dbjorge** [comment]
@v-tron Thanks for offering to review the changes! For exporting as an image, I think it would probably be realistic to use something like https://github.com/tsayen/dom-to-image to do that, but I think it would be more appropriate to use a separate PR for that; I'd recommend filing an issue to request that feature.

**Comment by Multigrain** [comment]
Great changes @dbjorge . I'm glad to see people are still finding use of this tool. Its been a few leagues since I've played but the new information looks correct. Whenever the rest of the guff information is available I can merge that too. You are welcome to take over the project if you'd like as I have no short term intentions of adding any major features myself. I'm still available and not too busy to review/merge updates though.

For the export to image function that would be useful. I always just manually screen captured it, but that would be more consistent for others having it as a feature.

Merged and I will build the changes to the static page sometime tonight.

**Comment by Multigrain** [comment]
Live should be updated. Make sure to force update to clear cache locally if images not updating (cntrl + f5)

**Comment by dbjorge** [comment]
Awesome, thanks @Multigrain!

**Pull request merged**
